In [1]:
import numpy as np
list=[1,2,3,4,5]
print (list[0])

1


In [2]:
testsuperlist=["john elder",True,2.5,1,5,8,True,False,"the best"]
for element in testsuperlist:
 if isinstance(element, str):
  print(element)

john elder
the best


In [3]:
np1=np.array([0,1,2,3,4,6,5,7,8,9])
print(np1)
print(np1.shape)

[0 1 2 3 4 6 5 7 8 9]
(10,)


In [4]:
np2=np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
np3=np.array(np1[::2])
print(np3)

[0 2 4 5 8]


In [6]:
import numpy as np
np4=np.zeros(5)
print(np4)

[0. 0. 0. 0. 0.]


In [7]:
np5=np.zeros((2,4))
print(np5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
np6=np.full((5),8)
print(np6)



[8 8 8 8 8]


In [9]:
np7=np.full((5,2),8)
print(np7)

[[8 8]
 [8 8]
 [8 8]
 [8 8]
 [8 8]]


In [10]:
my_list=[1,2,3,4,5]
np8=np.array(my_list)
print(np8) 

print(my_list[1])

[1 2 3 4 5]
2


In [11]:
np1=np.array([1,2,3,4,5,6,7,8,9,9])
print(np1[1:5])

[2 3 4 5]


In [12]:
print(np1[2:])
print(np1[:-2])
print(np1[-3:-1])

[3 4 5 6 7 8 9 9]
[1 2 3 4 5 6 7 8]
[8 9]


In [13]:
print(np1[1:5])
print(np1[1:5:2])
print(np1[::2])

[2 3 4 5]
[2 4]
[1 3 5 7 9]


In [14]:
import numpy as np
np2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2[1,2])
print(np2[0,1])
print(np2[0:1,1:3])
print(np2[0:2,1:3])


8
2
[[2 3]]
[[2 3]
 [7 8]]


In [15]:
np1=[-3,-2,-1,0,1,2,3,4,5,6,7,8,9]
print(np.sqrt(np1))

[       nan        nan        nan 0.         1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]


C:\Users\HerMajesty\AppData\Local\Temp\ipykernel_4740\3335893409.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


In [16]:
print(np.absolute(np1))

[3 2 1 0 1 2 3 4 5 6 7 8 9]


In [17]:
print(np.exp(np1))

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [18]:
print(np.min(np1))
print(np.max(np1))

-3
9


In [19]:
print(np.sign(np1))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


In [20]:
print(np.sin(np1))
print(np.cos(np1))

[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]
[-0.9899925  -0.41614684  0.54030231  1.          0.54030231 -0.41614684
 -0.9899925  -0.65364362  0.28366219  0.96017029  0.75390225 -0.14550003
 -0.91113026]


In [21]:
#create view and copy

np1=np.array([0,1,2,3,4,5])
#1 create a view(it will reflect to the original )
np2=np1.view()
print(f'Original NP1{np1}')
print(f'Original NP2{np2}')

np1[0]=41
print(f'Changed NP1{np1}')
print(f'Original NP2{np2}')




Original NP1[0 1 2 3 4 5]
Original NP2[0 1 2 3 4 5]
Changed NP1[41  1  2  3  4  5]
Original NP2[41  1  2  3  4  5]


In [22]:
#2 create a copy(the results didn't updated,it's just a copy)
import numpy as np
np1=np.array([0,1,2,3,4,5])

np2=np1.copy()
print(f'Original NP1{np1}')
print(f'Original NP2{np2}')

np2[0]=41 #here you can write "np1[0]=41" and see the result
print(f'Changed NP1{np1}')
print(f'Original NP2{np2}')

Original NP1[0 1 2 3 4 5]
Original NP2[0 1 2 3 4 5]
Changed NP1[0 1 2 3 4 5]
Original NP2[41  1  2  3  4  5]


In [23]:
import numpy as np
np1=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27])
print(np1)
print(np1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18 19 20 21 22 23 24
 25 26 27]
(27,)


In [24]:
np2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
print(np2.shape)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [25]:
np3=np2.reshape(2,3,2)
print(np3)
print(np3.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [28]:
np1=np.array([1,2,3,4,5,6,7,8,9,10])

for x in np1:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [29]:
np2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

for x in np2:
    print(x)


[1 2 3 4 5]
[ 6  7  8  9 10]


In [30]:
for y in x:
    print(y)

6
7
8
9
10
